server:
  port: 8080
  servlet:
    context-path: /api
  reactive:
    session:
      timeout: -1
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      password: ${mysql.password}
      username: ${mysql.username}
      url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?serverTimezone=Asia/Shanghai
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    async:
      request-timeout: -1
jwt:
  # 随便写一串复杂的字符串，长度至少32位
  secret: ${jwt.secret}
  # 过期时间，例如 86400000 毫秒 (24小时)
  expiration: 86400000

#mybatis-plus:
#  configuration:
#    log-impl: com.rag.ragserver.configuration.MybatisPlusOut
logging:
  level:
    com.rag.ragserver.mapper: info